### ISSUE TITLE
Template file Standard/.html not found

### ISSUE THREAD

**Issue by pauweh** [benjaminkott/bootstrap_package#538] opened 2018-07-25 21:03 UTC
typo3 v8.7.17 with php 7.1.15 and bootstrap_package v8.0.6 is running perfect.
Update to bootstrap_package 9.0.2 with very minor changes is running perfect, too.
Update to bootstrap_package 9.1 results an error:

Oops, an error occurred!
Tried resolving a template file for controller action "Standard->" in format ".html", but none of the paths contained the expected template file (Standard/.html). The following paths were checked: 
xxx/typo3conf/ext/bootstrap_package/Resources/Private/Templates/Page/, 
xxx/fileadmin/xyz/Bootstrap/Templates/Page/

The error page given is not very helpfull:
https://wiki.typo3.org/Exception/CMS/1257246929

Seems I am not the only one:
https://webdesign-forum.net/thread-4581.html

Can reproduce the error:
I have all running versions (v8.0.6, 9.0.2, 9.1) in extra folders. 
All settings and configurations are made without touching 
any file in the extension. 
So copy the an fodler with an older version will work.
Copy the extension folder for 9.1 will produce the error.

Will try now to find if all the settings are ok with the new version 9.1.
But has anybody a hint where to look first?

**Comment by benjaminkott** [comment] 2018-07-26 11:45
@pauweh i think you are hitting the the autolookup of the templates that has a problem with your custom configuration. Instead of mapping each and every page template it is now enough to just place a template in the directory that is matching your backendlayout.

it could also be that you did not select a backendlayout in the first place. then just select a backendlayout in the page properties and select another one for all pages below. have a look at the changes here:

https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.typoscript#L88-L114

**Comment by pauweh** [comment] 2018-07-27 17:01
Thank you for your fast and helpfull answer.
Did select a backendlayout/subpages for the rootpage 
and for a page with subpages.
Tested default layouts and my own layouts: Error is the same.

Copied v9.0.2 back into ext-folder: All is working as before like a charm.

If the error comes from the new autoload-feature, I would guess its a good idea
to let it enable/disable in the package configuration, because this update
stops the whole website from working.

PS. 
When looking at the backendlayouts in page properties 
the icons there are shown in different sizes now with v9.1.1. 
The standard default layouts icons are shown twice as large 
as the icons for my own backendlayouts.

**Comment by benjaminkott** [comment] 2018-07-27 18:45
@pauweh can you please dump me your typoscript configuration here for the custom backend layouts?

**Comment by pauweh** [comment] 2018-07-30 11:07
Here it is. I can see, that the definitions in stdWrap.cObject are making some difference.


![bootstrap](https://user-images.githubusercontent.com/23434241/43393885-f80c3982-93f8-11e8-86cb-fa15ee859cdf.jpg)

**Comment by benjaminkott** [comment] 2018-07-30 11:52
Ok, from that i can see is that your backend layouts are defined as records in the database. 
The mapping was removed completely and is not nessesary anymore. It will not autodiscover your templates and they need to follow a naming convention. So you will not need to adjust the setup in the future again. Please see comment before template resolving.

```
Template names will be generated automaticly by converting the applied
backend_layout, there is no explicit mapping nessesary anymore.

BackendLayout Key
subnavigation_right_2_columns -> SubnavigationRight2Columns.html

Backend Record
uid: 1 -> 1.html

Database Entry
value: -1 -> None.html
value: pagets__subnavigation_right_2_columns -> SubnavigationRight2Columns.html
```

How to restore compatability:
1. 
Delete custom mapping `page.10.templateName.stdWrap`

2.
Rename templates in filesystem

```
All3Columns.html -> 1.html
OneRow3Columns.html -> 2.html
2Columns5050NaviRight.html -> 3.html
....
```

If you add new backendlayouts as records just place a file with the `UID` as filename and TYPO3 will find the templates for you.

If you prefer speaking names for your templates you should move them to PageTsConfig like here.
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TsConfig/Page/Mod/WebLayout/BackendLayouts/subnavigation_left_2_columns.tsconfig#L7

The key also becames the name of the template

```
subnavigation_left_2_columns  -> SubnavigationLeft2Columns.html
```

**Comment by pauweh** [comment] 2018-07-30 16:09
Thank you again for your fast and precise answer.
BUT:
1. Solution
Rename speaking names back to numbered once is a regression back to software development in the last century, no in the last millenium. I have very much of  these templates. And when changing the names 
on each future editin I have to search which number is which layout? 
Sorry to say this, but this is more than stupid!!
Wont go back renaming my variables as non speaking numbers or my filenames as non-speaking ones.

2. Solution - Setting backend-layout key to find filenames.
This solution is even more stupid than the 1. above.

My backend-layout already have this speacking names. 
They are the same as the filenames for the templates.
The ONLY thing to achive this at the moment is one line
page.10.templateName.stdWrap.cObject.9.value = OneRow2Columns-NavRight
where 9 is the id of the layout. And I still can use the typo3 GUI for editing the backend-layouts.

In the future I shall take the text-configuration, add an additional keyname 
and write this into pageTS to have an additional keyname which tells typo3
to combine a backend-layout OneRow2Columns-NavRight with its template file
OneRow2Columns-NavRight.html by a key one_row_2_columns-_nav_right??
Is this a brain jogging test or is this modern software development?
Or is it just stupid?

3. Solution proposed
Sorry for the above - but I hate staggering non-sense making autoxyz feature solutions 
more complicated than before.
Why do you not just make the following typoscript line auto-templating?
This line is already not very helpfull and is betting for improvement ;-)):
page.10.templateName.stdWrap.cObject.9.value = OneRow2Columns-NavRight

So why not just tells the system that the backend-layout named
OneRow2Columns-NavRight (id does not matter) should use the template file with the name
OneRow2Columns-NavRight.html?

This would be a simple and effective auto-templating: Just define backend-layouts 
with typo3 build in GUI and name them. The NAME of the be-layout defines the filename searched for.
Easy and clear - isnt it?

AND it should be update compatible with older bootstrap_packages.

**Comment by benjaminkott** [comment] 2018-07-31 08:40
Dear @pauweh, i have to disagree.
First of I am really open for suggestions and I’m trying to help everyone with their problems and even to find better solutions. BUT if a conversation starts with “this or that is stupid”, “last century/millennium” my willingness to help reaches fast level zero.
So, let’s go through your comments.

1. Mapping Template Names automatically to the identifier. First, this is not a regression – this is a change of behavior – and that’s totally fine. The patch itself was marked as breaking and an upgrade path was provided. Documentation could be better I agree. There is no need to rename for variables to something something, just delete the mapping, rename the files.
2. It´s best practice to provide backend layout configuration via PageTsConfig. Since it has a lot of advantages over the legacy database stored configurations. It´s deployable, easy to transfer and you can bundle them easy with your sitepackage. You do not need to Adjust your mapping if your database is diverged between staging/development/production system since you need to provide a custom unique identifier for the configuration. Even the backend module helps you to extract the configuration. 

This is not a brain jogging test, nor is it stupid. It´s about being explicit and building more stable, reliable setups. If you would export your configuration/pagetree and move it to a different instance it would completely break your setup because the uid´s of your connected backend layouts will change since there already could exist templates in the target instance. Having unique identifiers that are defined outside the database is important to make configurations portable and reusable. Mapping to uid´s in the database is not.

The title of the record can not be the identifier:

- May be translated
- Is not unique, it´s not static
- Renaming’s of the record in the database would not rename files, this can break your site.

I highly recommend moving backend layout configurations to PageTsConfig.
I highly recommend to package custom configuration in a sitepackage

Please see: 

- https://www.sitepackagebuilder.com/
- https://speakerdeck.com/benjaminkott/the-anatomy-of-typo3-sitepackages
- https://www.youtube.com/watch?v=HtBmim7pc0o&list=PL-sDBIrOKGOZF7LK7Pcq2kH7FpbKvFsgK


If you still think thats *stupid*.
```
page.10.templateName >
page.10.templateName = TEXT
page.10.templateName {
    stdWrap.cObject = CASE
    stdWrap.cObject {
        key.data = pagelayout
        default = TEXT
        default.value = Default
    }
}
```

**Comment by pauweh** [comment] 2018-08-10 13:14
Thank you again for your patience.
All your "improvements" are for NEW installations.
Please keep in mind, that we are talking about an UPDATE from v9.0 to v9.1!!
Currently the update is stopping the website completely.
The update causes problems where your solutions are way too complicated and unnecessary
for websites already running without errors. That is the point.
But lets look into the future ;-).
Your suggested workaround above is pretty good and the website is running with it.
But you did rename the Default templates. All the hundreds and thousands of pages
with the old backend-layout keys now are out-of-order: In the backend the pages content
is now displayed in the Default backend-columns, where the default layouts are used. 
Thats horrible for backend-editors.
The backend-layout appearance now is out-of-order, too, see screenshot.

![backend-layout](https://user-images.githubusercontent.com/23434241/43959652-cf0763da-9caf-11e8-83a6-492adac47142.jpg)

So the frontend default layouts are no longer working.
All the template.html files have to be renamed.
And the backend is unusable.

**Comment by noll1** [comment] 2018-08-31 10:08
I have the same problem that @pauweh described above.
You renamed the Default templates and now no page will be render.
I've done following mapping as workaround for other users with the same problem:
`page.10.templateName >
page.10.templateName = TEXT
page.10 {
    templateName.stdWrap.cObject = CASE
    templateName.stdWrap.cObject {
    	# Mapping old layout names to new ones
    	key.data = pagelayout
		
		pagets__default_clean = TEXT
		pagets__default_clean.value = Clean
		
		pagets__default_2_columns = TEXT
		pagets__default_2_columns.value = 2Columns
		
		pagets__default_2_columns_25_75 = TEXT
		pagets__default_2_columns_25_75.value = 2Columns2575
		
		pagets__default_2_columns_50_50 = TEXT
		pagets__default_2_columns_50_50.value = 2Columns5050
		
		pagets__default_2_columns_offset_right = TEXT
		pagets__default_2_columns_offset_right.value = 2ColumnsOffsetRight
		
		pagets__default_3_columns = TEXT
		pagets__default_3_columns.value = 3Columns
		
		pagets__default_subnavigation_right = TEXT
		pagets__default_subnavigation_right.value = SubNavRight
		
		pagets__default_subnavigation_right_2_columns = TEXT
		pagets__default_subnavigation_right_2_columns.value = SubNavRight2Columns
		
		pagets__default_subnavigation_left = TEXT
		pagets__default_subnavigation_left.value = SubNavLeft
		
		pagets__default_subnavigation_left_2_columns = TEXT
		pagets__default_subnavigation_left_2_columns.value = SubNavLeft2Columns
		
		pagets__special_start = TEXT
		pagets__special_start.value = SpecialStart
		
		pagets__special_feature = TEXT
		pagets__special_feature.value = SpecialFeature
		
		default = TEXT
		default.value = Default
    }
}`
But in the backend I see also [ INVALID VALUE ... ].

**Comment by noll1** [comment] 2018-08-31 10:13
I have the same problem that @pauweh described above.
You renamed the Default templates and now no page will be render.

I've done following mapping as workaround for other users with the same problem:

```
page.10.templateName >
page.10.templateName = TEXT
page.10 {
    templateName.stdWrap.cObject = CASE
    templateName.stdWrap.cObject {
    	        # Mapping old layout names to new ones
    	        key.data = pagelayout
		
		pagets__default_clean = TEXT
		pagets__default_clean.value = Clean
		
		pagets__default_2_columns = TEXT
		pagets__default_2_columns.value = 2Columns
		
		pagets__default_2_columns_25_75 = TEXT
		pagets__default_2_columns_25_75.value = 2Columns2575
		
		pagets__default_2_columns_50_50 = TEXT
		pagets__default_2_columns_50_50.value = 2Columns5050
		
		pagets__default_2_columns_offset_right = TEXT
		pagets__default_2_columns_offset_right.value = 2ColumnsOffsetRight
		
		pagets__default_3_columns = TEXT
		pagets__default_3_columns.value = 3Columns
		
		pagets__default_subnavigation_right = TEXT
		pagets__default_subnavigation_right.value = SubNavRight
		
		pagets__default_subnavigation_right_2_columns = TEXT
		pagets__default_subnavigation_right_2_columns.value = SubNavRight2Columns
		
		pagets__default_subnavigation_left = TEXT
		pagets__default_subnavigation_left.value = SubNavLeft
		
		pagets__default_subnavigation_left_2_columns = TEXT
		pagets__default_subnavigation_left_2_columns.value = SubNavLeft2Columns
		
		pagets__special_start = TEXT
		pagets__special_start.value = SpecialStart
		
		pagets__special_feature = TEXT
		pagets__special_feature.value = SpecialFeature
		
		default = TEXT
		default.value = Default
    }
}
```

But in the backend I see also [ INVALID VALUE ... ].

**Comment by noll1** [comment] 2018-09-05 11:53
I've got the solution.
@benjaminkott already intended the mapping of old layouts to the new one.
You can found this in the class "typo3conf/ext/bootstrap_package/Classes/Updates/BackendLayoutUpdate.php".
When you click in the Install Tool on "Run Upgrade Wizard" there is a task to migrate the backend layouts.
After execution the right layouts are selected in the backend and your sites will render successfully.

**Comment by gilbertsoft** [comment] 2021-08-17 18:16
As mentioned if you use the Upgrade Wizard like also describe in the TYPO3 docs there should be no issue. I'm going to close this issue now.

**Closed by gilbertsoft** 2021-08-17 18:16 UTC
Labels: question
