### ISSUE TITLE
Performance problem after updating from 12.0.3 to 12.0.4

### ISSUE THREAD

**Issue by mediaessenz** [benjaminkott/bootstrap_package#1128] opened 2022-01-07 16:10 UTC
# Bug Report

## Description

After updating EXT:bootstrap_package from 12.0.3 to 12.0.4 I got performance problems in my TYPO3 backend.

Every call takes 2-5 times longer than before.

After comparing the differences between the two releases, I tried to revert each part of it.
In the end I found out, as crasy it may sounds, that the cause of the problem is the change of how the typoscript of the different content is included!

After reverting all 
```
@import 'EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Element/*.typoscript'
```
inside Configuration/TypoScript/ContentElement/setup.typoscript back to 
```
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Element/*.typoscript">
```
it works as fast as before.

## Versions

TYPO3 10.4.22
bootstrap_package 12.0.4

**Comment by gilbertsoft** [comment] 2022-01-08 11:53
Thanks for your report. I'm already discussing this issue with the core team. One question is if you import the bootstrap package setup.typoscript multiple times. Please check this in the template analyzer.

**Comment by gilbertsoft** [comment] 2022-01-08 17:58
See also https://typo3.slack.com/archives/C03AM9R17/p1641638049008600. There will be a fix in the core for this, maybe I will also revert the a part of the change here in the meantime.

**Comment by mediaessenz** [comment] 2022-01-08 18:21
Typoscripts of EXT:bootstrap_package included only once. The issue exists independent of the cache state.

I have made some measurements in two of my backend modules, both based on extbase:
Module "Orders": 
BP 12.0.3: 3.7s
BP 12.0.4: 12.3s 

Module "Invoices":
BP 12.0.3: 3.6s
BP 12.0.4: 12.1s

In the average, it takes tree times longer, after updating BP from 12.0.3 to BP 12.0.4.

It also seem to affects the frontend.
A uncached search result tooks 6.6s with BP 12.0.3. and 16.6s with BP 12.0.4

**Comment by gilbertsoft** [comment] 2022-01-09 15:08
Thanks for the additional information, looks really bad but also with BP 12.0.3 and I'm wondering which additional issues you have. Is the backend everywhere so slow or just with your modules?

**Comment by mediaessenz** [comment] 2022-01-09 16:23
The "Orders" module collects data of around 13.000 orders with relations to its positions. This take a while.
Other modules are faster, but comparing to my local development system much slower as well.
Opening the page module e.g. takes about 4s (development system <1s).
But maybe it's a compare between apples and pinnaples.
My local development system has a 3,6 GHz 8-Core Intel Core i9 with 32 GB RAM.
My server has 8-Cores of a 2 GHz AMD CPU with 16 GB RAM shared with around 20 other websites.

**Comment by gilbertsoft** [comment] 2022-01-09 19:14
> Opening the page module e.g. takes about 4s

Is there a notable difference between BP .3 and .4?

> But maybe it's a compare between apples and pinnaples.

Of course, comparing two different systems is not very useful. And local development systems are usually faster than production servers.

**Comment by mediaessenz** [comment] 2022-01-12 18:28
> Is there a notable difference between BP .3 and .4?

Yes
.3: 4s
.4: 12s

**Comment by mediaessenz** [comment] 2022-01-13 10:31
I just checked it with an other system (a TYPO3 11.5.5) as well and got similar results.
Loading the page module with the identical page open takes under
BP 12.0.3: ~1s
BP 12.0.4: ~4s

**Comment by basc** [comment] 2022-01-18 14:04
We also have noticed performance problems in the frontend after updating from 12.0.3 to 12.0.4.

I have compared BP 12.0.3 and 12.0.4 on our production server.
Enviroment: Windows Server, PHP 7.4, Typo3 10.4.23

How long does it take to load the main page of our website.
I have refreshed the page in the browser a few times, so it is not the first call after clearing the caches.

* BP 12.0.3
Average duration in Chrome DevTools: 300ms. While I am logged in backend. (Typo3 adminPanel shows 150ms)
Average duration in Chrome DevTools: 150ms. While I am not logged in in backend.

* BP 12.0.4
Average duration in Chrome DevTools: 650ms. While I am logged in backend. (Typo3 adminPanel shows 450ms)
Average duration in Chrome DevTools: 500ms. While I am not logged in in backend.

Every call takes around 2-3 times longer than before.

If i revert the changes from import to <INCLUDE_TYPOSCRIPT>, than BP 12.0.4 is as fast as BP 12.0.3

**Comment by gilbertsoft** [comment] 2022-01-18 15:35
Thanks for your feedback! It looks like reverting that change would really make sense then, will take care...

**Comment by chequille** [comment] 2022-01-23 18:51
Hi Everybody,
I just wanted to report the bad performance as well and saw this entry.
I do have the same problems and are running as well 12.0.4
Did install now 12.0.3 and it is OK again.
Best regards,
Chequille

**Comment by mediaessenz** [comment] 2022-05-06 09:09
This problem is solved with 12.0.5, which uses <INCLUDE_TYPOSCRIPT> again.

**Comment by gilbertsoft** [comment] 2022-05-09 14:30
fyi this patch https://review.typo3.org/c/Packages/TYPO3.CMS/+/74285 or a follow up should finally resolve the issue directly in the core.

**Comment by supercaccia** [comment] 2023-02-01 08:20
> fyi this patch https://review.typo3.org/c/Packages/TYPO3.CMS/+/74285 or a follow up should finally resolve the issue directly in the core.

@gilbertsoft @lolli42 @benjaminkott 

This core patch was abandoned. 
In my opinion this bug has not been fixed. 
Is it really a core bug? 
How can this bug be fixed?

Thanks!

**Comment by lolli42** [comment] 2023-02-01 20:03
The core issue *is* fixed in v12: The 'abandoned' patch has been split into smaller pieces and merged core in multiple chunks. See patches attached to issue https://forge.typo3.org/issues/97816 for more details. The @import resolver is in v12 class `TYPO3\CMS\Core\TypoScript\IncludeTree\TreeFromLineStreamBuilder`.

The reason for slow @import was the usage of symfony finder - I rewrote the logic in v12 and implemented a 'native' solution that is much quicker - at least on-par with INCLUDE_TYPOSCRIPT now. Plus v12 TypoScript comes with a much more effective cache layer in the Frontend. I considered a backport of the @import rewrite to v11, but the new solution is slightly more restrictive in what it finds, so a backport risks breaking v11 instances with bugfix releases, so i ditched the idea again.

Note with v12, @import happily works within TypoScript [foo = bar] conditions, which eliminates the last legit reason to use INCLUDE_TYPOSCRIPT as well.

**Comment by basc** [comment] 2023-04-28 10:52
I can confirm that this issue is solved with Typo v12.
The performance with '@import' is now as fast as with 'INCLUDE_TYPOSCRIPT'.
Thanks!

**Closed** 2023-06-21 15:25 UTC
Labels: bug, need feedback
