### ISSUE TITLE
Workspace: "Ooops error" for card group elements

### ISSUE THREAD

**Issue by lisanoffke** [benjaminkott/bootstrap_package#954] opened 2020-11-16 09:57 UTC
**Description**
Tested with TYPO3 9.5.22

For "card group elements" an "Ooops error" is output in the workspace frontend (see screenshot below):
"Oops, an error occurred! Code: xxx"
In our case elements of the type "card group" are currently affected.
In the backend all looks fine, but we get no output in the frontend.

In the "live version" of the specific page everything looks fine (backend and frontend), but the elements must be editable and checked in the workspace.

**Question:**
Editors are supposed be able to edit card groups in the workspace and see the result in the frontend.
Any ideas why there is no correct frontend output for card group elements in a workspace?

<img width="1039" alt="error_card-group_in_workspace" src="https://user-images.githubusercontent.com/66476158/99238265-cf1c2400-27f9-11eb-9486-a37cb9444ca4.png">

**Comment by gilbertsoft** [comment] 2020-11-16 12:33
Hi @lisanoffke, just tested latest Bootstrap Package with ext:workspaces and I'm not able to reproduce your error. Can you please check your logs and post more information like a backtrace.

**Comment by ischmittis** [comment] 2021-01-12 21:32
Hey @gilbertsoft, attached a log. 

It seams that somehow a request against a missing column is made.
[typo3_6e1f96175b.log](https://github.com/benjaminkott/bootstrap_package/files/5804908/typo3_6e1f96175b.log)

**Comment by ischmittis** [comment] 2021-01-27 13:25
Can we somehow speed up the analysis process?

**Comment by netbrothers-tr** [comment] 2021-01-27 19:55
Could this be related to [TYPO3 Bug #81208](https://forge.typo3.org/issues/81208)?

**Comment by ischmittis** [comment] 2021-02-05 17:00
[TYPO3 Exception.pdf](https://github.com/benjaminkott/bootstrap_package/files/5934081/TYPO3.Exception.pdf)
A more detailed output of the error

**Comment by gilbertsoft** [comment] 2021-08-17 18:35
Like mentioned this issue is related to a core bug and is fixed since 10.4.16. It was not backported to 9.5. I'm going to close this issue now as it looks not related to this extension.

**Closed by gilbertsoft** 2021-08-17 18:35 UTC
Labels: bug, could not reproduce, need feedback
