### ISSUE TITLE
 target="{mainnavigationItem.target}" don't work

### ISSUE THREAD

**Issue by supercat1510** [benjaminkott/bootstrap_package#442] opened 2017-04-13 13:00 UTC
New install with Typo3 8.7 LTS.
Bootstrap_package 8.0.0
Standard Template without Script changes.

- Add target to a Page.
- Save & Reset Cache
- Reset Homepage
The target is empty.

Than we try change to "External link" with target - is also empty.

**Comment by florianstieglbauer** [comment] 2017-04-21 09:57
This works for me:
{mainnavigationItem.data.target}

**Comment by florianstieglbauer** [comment] 2017-04-21 10:03
Use: {mainnavigationItem.**data**.target}

My solution:
{f:if(condition: '{mainnavigationItem.data.target}', then: 'target="{mainnavigationItem.data.target}"')}

**Comment by benjaminkott** [comment] 2017-05-07 17:36
@supercat1510 @florianstieglbauer issue could be confirmed, this is a issue in the TYPO3 core. 
Behavior is fixed and patch is pending, as soon as the patch is merged the targets will work as expected.

https://review.typo3.org/#/c/52735/

**Comment by benjaminkott** [comment] 2017-05-07 17:37
@supercat1510 @florianstieglbauer i will close the issue here, thx a lot for reporting.

**Closed by benjaminkott** 2017-05-07 17:37 UTC
Labels: bug, TYPO3 CMS
