### ISSUE TITLE
Error: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()

### ISSUE THREAD

**Issue by RudStar** [benjaminkott/bootstrap_package#1234] opened 2022-12-14 11:00 UTC
[x] TYPO3 v10.4.31 -  v10.4.33 LTS
[x] bootstrap_package v12.0.5 - v12.0.7
[x] PHP 7.4
[x] Multiple websites hosted by different providers.

With bootstrap_package from v12.0.5 on, an error is output when calling the "Report" page. 
Also, the Upgrade Wizard does not work anymore.

![Bildschirmfoto 2022-12-14 um 11 59 55](https://user-images.githubusercontent.com/22195364/207577846-7685c50c-a039-425c-9dd1-c131d55c4d6d.png)

![Bildschirmfoto 2022-12-14 um 12 00 29](https://user-images.githubusercontent.com/22195364/207577859-37d29f2f-87c0-482a-83a5-e0f5a9be71c8.png)

![TYPO3-CMS-10-4-33](https://user-images.githubusercontent.com/22195364/207581507-80bf4526-231c-4487-b054-721e80bb8e38.png)

**Comment by Typine3** [comment] 2022-12-15 11:06
I found out that if I deactivate bootstrap_package 12.0.7, update to typo3 10.4.33, and activate bootstrap 12.0.7 afterwards, everything is fine...

**Comment by RudStar** [comment] 2022-12-15 11:18
@Typine3 And can you call up the "Reports" page without errors? Specifically the "Status Report" subpage.

**Comment by Typine3** [comment] 2022-12-15 11:25
Oh, I just tested it - both 
bootstrap_package 12.0.5 with Typo3 10.4.32 (Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne() )and 
bootstrap_package 12.0.7 with Typo3 10.4.33 (Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()) 
produce an error like you described when I call up "Reports"!
"Everything is fine" only in my frontends, sorry...

**Comment by Hawkeye1909** [comment] 2023-05-23 14:09
Hi!

Just ran into this. This seems to affect only non-composer installations.

I have replaced the affected line 147 in AbstractUpdate.php with the following code:
```
        /** @phpstan-ignore-next-line */
        if (method_exists($result, 'fetchAllAssociative')) {
            return $result->fetchAllAssociative();
        } else {
            return $result->fetchAll(\PDO::FETCH_ASSOC);
        }
```
If there's any need for a pull request, I can make one.

**Comment by oliverklee** [comment] 2023-05-31 12:13
#1252 looks like a duplicate of this ticket.

**Comment by RudStar** [comment] 2023-05-31 12:24
from [Hawkeye1909](https://github.com/Hawkeye1909) fixes the bug. Thanks!

**Comment by benjaminkott** [comment] 2023-06-21 15:16
resolved with https://github.com/benjaminkott/bootstrap_package/commit/d43358be5cb8ace2c5e3239504836c988bb61155

**Closed by benjaminkott** 2023-06-21 15:16 UTC
Labels: bug
