### ISSUE TITLE
Missing RTE toolbar

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#141] opened 2015-02-28 13:07 UTC
Hi @benjaminkott and @froemken!
The commit 884dc4049c8fc21d0678f210aa13abb287ce13fc made the toolbar of the RTE disappear in my installations.

The problem resides in the missing RTE.default.toolbarOrder setup that has been commented in this commit.

Is it working for you guys?

**Comment by benjaminkott** [comment] 2016-06-26 01:26
i think we can close this, should be fixed cannot reproduce it anymore ;)

**Closed by benjaminkott** 2016-06-26 01:26 UTC
