### ISSUE TITLE
Problem with the Timeline element in workspaces

### ISSUE THREAD

**Issue by lisanoffke** [benjaminkott/bootstrap_package#897] opened 2020-06-05 12:54 UTC
# Bug Report

## Prerequisites

* [ not tested] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ yes] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

As soon as I add a new timeline item in a workspace, the date of all existing timeline items is moved forward by one year. If the item is edited directly in Live backend, we do not have the problem. Here the workspace does not seem to be able to cope with the timeline element.

Tested with TYPO3 9.5.18

## Steps to Reproduce

1. Open a TYPO3 9.5.18 and switch to a workspace.
2. Open an existing timeline element and add a new timeline item with current date.
3. Check previous timeline items in backend and frontend-preview.

### Expected behavior

1. Open a TYPO3 9.5.18 and switch to a workspace.
2. Open an existing timeline element and add a new timeline item with current date.
3. A new timeline item was added, previous items did not change.

### Actual behavior

1. Open a TYPO3 9.5.18 and switch to a workspace.
2. Open an existing timeline element and add a new timeline item with current date.
3. Backend: All previous items have a new date (one year earlier) which can also be verified in the frontend (workspace preview)
--> Problem at hand: Timeline items which were not touched have a new date.

### Screenshots

[If applicable, add screenshots to help explain your problem.]

## Versions

You can get this information from executing `composer show` at the command line
if your TYPO3 installation is composer based, otherwise the version number will
be shown in the extension manager.

**Comment by benjaminkott** [comment] 2020-06-05 14:23
Checked the issue but i am unable to reproduce the issue locally with workspaces. Also in preview and records everything looks as it should be and the not adjusted dates were not updated.

![image](https://user-images.githubusercontent.com/3243119/83887516-d61e1100-a748-11ea-8b7d-f3166f814c2b.png)

**Comment by lisanoffke** [comment] 2020-06-22 09:46
OK, if no one is able to reproduce this issue, we will have to check our implementation once more.

**Comment by gilbertsoft** [comment] 2021-08-17 18:31
I'm going to close this issue now because there was no more feedback and the issue was not reproducable.

**Closed by gilbertsoft** 2021-08-17 18:31 UTC
Labels: bug, need feedback, evaluation
