### ISSUE TITLE
Navigation won't autoclose on next submenu selection

### ISSUE THREAD

**Issue by dduers** [benjaminkott/bootstrap_package#1052] opened 2021-08-17 03:00 UTC
Hello,

Installed bootstrap_package 12.0.1

In the mobile version, once a top level navigation entry is opened and then select another top level navigation entry, the previous selected top level entry is closed, but not marked as such.

Cheers, Dduers

**Comment by gilbertsoft** [comment] 2021-08-17 14:10
@dduers Thanks for your report. I'm currently not able to reproduce your issue, tested on Android with Google Chrome. Can you please provide some more information and maybe also screen shots of the wrong behaviour.

**Comment by benjaminkott** [comment] 2021-08-19 09:09
@dduers found the issue, will be fixed in next release

**Closed** 2021-08-19 09:09 UTC
Labels: bug, need feedback
