### ISSUE TITLE
include CSS

### ISSUE THREAD

**Issue by blackbasket** [benjaminkott/bootstrap_package#894] opened 2020-06-03 10:32 UTC
Hi,

I am new with typo3 and it looks I am to stupid to include a custom css file into bootstrap_package.

I tried 
`page.includeCSS {
    styles=fileadmin/Css/custom.css
}`

as well as

`page.includeCSS.custom = fileadmin/Css/custom.css`. My first attempts were with another path "EXT:...", but after much of searching I tried the fileadmin path as well.

I added the lines into "setup" in the template.

The css never is loaded. If I chage the scss-file from the bootstrap_package it is working immediately.

Regards,
Marcel

**Comment by gilbertsoft** [comment] 2020-06-03 10:39
Checkout https://www.sitepackagebuilder.com/ which shows the way to go

**Comment by olivermeckel** [comment] 2020-06-03 11:05
Thank you for your feedback. You are absolutely right. And it's not a bug. I found the following for pages. I think it's the same for translated content elements.

`DataHandler: “sorting” and “pid” parameters of translations are always kept in sync one-to-one for translated pages. Translated pages cannot be moved themselves.`

**Comment by blackbasket** [comment] 2020-06-03 13:55
I'm sorry, but I still don't get it...

I added the css in the setup.ts, but it still is not used...

`page {
    includeCSS {
       theme = EXT:rbk2020site/Resources/Public/Scss/Theme/theme.scss
       myCss = EXT:rbk2020site/Resources/Public/Css/custom.css
    }`

**Comment by olivermeckel** [comment] 2020-06-03 14:06
Can you try and delete the frontend cache

**Comment by blackbasket** [comment] 2020-06-03 14:10
I have tried several times :(

**Comment by olivermeckel** [comment] 2020-06-03 14:13
Do you have included the static file from your extension in your template in the backend? Their is no autoload in the sitepackages …

**Comment by blackbasket** [comment] 2020-06-03 14:15
Yes, I have included it.

![image](https://user-images.githubusercontent.com/64146687/83647592-5b70bc80-a5b5-11ea-93dd-09d4c342322b.png)

**Comment by olivermeckel** [comment] 2020-06-03 14:27
you should not use fluid_styled_content with bootstrap_package
hard to help on the distance …
i use sitepackages myself and everything works fine.
Have you checked your site with template analyzer in the backend and with developer tools in frontend? Mayby it's just a typo

**Comment by blackbasket** [comment] 2020-06-03 14:36
No, I only "loose" the fluid design on a content element... I have to learn much more about typo3, but I did not think that using a custom css can be such a challenge ;)

**Comment by olivermeckel** [comment] 2020-06-03 14:42
i can reproduce the problem when i add fluid_styled_content
Delete "Fluid content elements" and "Fluid Content Elements CSS" from the list.
It overrides the css and the content elements of bootstrap_package and your extension

**Comment by blackbasket** [comment] 2020-06-03 14:50
nein, leider nicht... ich hatte schon mal alles rausgeworfen....

**Comment by blackbasket** [comment] 2020-06-03 15:29
I think the fluid elements cannot be the problem, because it should not even work in this case if I change the scss-file from the bootstrap_package itself, shouldn't it?

**Comment by medarob** [comment] 2020-06-03 15:40
Any errors in the console? A missing *.css file?
Have you checked the sourcecode of the page and is your custom CSS present? If so, does the link work?

**Comment by blackbasket** [comment] 2020-06-03 15:52
I do not see any errors in the console. There are two warnings as highest. "TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher: Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign."

If I look into the source code two css files are referenced. One from the news extension and the other one from "typo3temp/.../merged*". But the options I set are not used.

**Comment by medarob** [comment] 2020-06-03 16:00
Is your custom css code inside the merged* CSS file?

**Comment by olivermeckel** [comment] 2020-06-03 16:03
Set the following constants for developing in typo3. So the scss, css and js files don't get merged and compressed and you can check your code much easier.

`config {
    no_cache = 1
    compressJs = 0
    compressCss = 0
    concatenateJs = 0
    concatenateCss = 0
}`

**Comment by blackbasket** [comment] 2020-06-03 16:04
No, it was not. I have it working now. I changed the file from css to scss.

**Comment by blackbasket** [comment] 2020-06-03 16:05
Thanks for all your help!

**Comment by medarob** [comment] 2020-06-03 16:05
:-)

**Comment by brandwalla** [comment] 2020-06-04 12:23
@blackbasket which of the Typoscript statements worked for you?

**Comment by blackbasket** [comment] 2020-06-04 14:10
> `page { includeCSS { theme = EXT:rbk2020site/Resources/Public/Scss/Theme/theme.scss myCss = EXT:rbk2020site/Resources/Public/Scss/Theme/custom.css }`

This one works... But I think all would have worked if I realized that I tried to include an scss-File as css ;)

**Comment by brandwalla** [comment] 2020-06-04 17:45
Excellent, thank you @blackbasket

**Comment by benjaminkott** [comment] 2020-06-05 07:21
Hey everyone, seems the issue has been resolved. I am closing this issue now, feel free to open a new one.

**Closed by benjaminkott** 2020-06-05 07:21 UTC
Labels: question
